name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        architecture: [x64, arm64] # macOS supports ARM64, Windows supports x64
      exclude:
        - os: windows-latest
          architecture: arm64 # Windows ARM64 is not supported in GitHub Actions

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the app (test build)
        run: |
          python app/inspector.py &
          sleep 10
          pkill -f inspector.py
